[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aclds"
dynamic = ["version"]
description = "Android Credential Leakage Detection System V2"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Veera bhadhra" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "reportlab>=4.0.0",
    "matplotlib>=3.5.0",
    "tabulate>=0.8.9",
    "PySide6>=6.0.0"
]

[project.scripts]
aclds = "main:main"

[tool.setuptools]
packages = ["static_analysis", "dynamic_analysis", "correlation", "utils", "ui"]
py-modules = ["main", "gui", "__version__"]

[tool.setuptools.dynamic]
version = {attr = "__version__.VERSION"}
